export enum UICOMPONENTS{
    MAINMENU = "MAINMENU",
    CUSTOMERINVOICE = "CUSTOMERINVOICE",
    CUSTOMERS = "CUSTOMERS",
    REPORTS = "REPORTS"
}

export enum STORAGEVALUES{
    CUSTOMER = "customers",
    CUSTINVOICES = "customerinvoices",
}